version: 2.1
jobs:
  build-and-test:  
    docker:
      - image: cimg/node:14.16.1
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: ssh o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP
workflows:
  build-deploy:
    jobs:
      - build:
        filters:
         branches:
           only: master

