version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/tmp
    docker:
      - image: cimg/node:14.16.1
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: ssh -o StrictHostKeyChecking=no $root@$165.232.150.135 'cd production; git checkout master; git pull; npm install; npm run start:production;'
