version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: cimg/node:14.16.1
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install python 2.7
      - run: ln -s /usr/bin/python2.7 /usr/bin/python
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP 'cd prodution; git checkout master; git pull; npm install start:prodution;'
workflows:
  build-deploy:
    jobs:
      - build:
        filters:
         branches:
           only: master

